version: "3.4"
services:
  monitor:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    environment:
      PARITY_URL: "${PARITY_URL}"
      PARITY_REQUEST_INTERVAL_SECONDS: "${PARITY_REQUEST_INTERVAL_SECONDS}"
      COMPARE_WITH_ETHERSCAN: "${COMPARE_WITH_ETHERSCAN}"
    ports:
      - "3000:3000"
    volumes:
      - "../:/opt/app"
  test:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - "../:/opt/app"
    command: sh -c "
      npm run lint
      && npm run format "
