version: "3.4"
services:
  monitor:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    environment:
      PARITY_URL: http://parity.stage.san:30954
      PARITY_REQUEST_INTERVAL_SECONDS: 10
    ports:
      # port for checking health.
      - "127.0.0.1:3000:3000"
    entrypoint: "/bin/sh"
    command: ["-c", "npm start"]
